package codeslist

import (
	"github.com/hosts-guru/OTAModels-golang"
)

// SecurityFeature Identifies security features of the services, meeting rooms, guest rooms, and restaurants
// of a property.
const (
	SecurityFeatureAudibleAlarmSmokeDetectorsInGuestRooms                   otamodel.EnumString = "Audible alarm smoke detectors in guest rooms"
	SecurityFeatureAudibleAlarmsInHallways                                  otamodel.EnumString = "Audible alarms in hallways"
	SecurityFeatureAudibleAlarmsInPublicAreas                               otamodel.EnumString = "Audible alarms in public areas"
	SecurityFeatureAutoLinkToFireStation                                    otamodel.EnumString = "Auto link to fire station"
	SecurityFeatureAutomatedExternalDefibrillatorAEDOnSite                  otamodel.EnumString = "Automated External Defibrillator (AED) on-site"
	SecurityFeatureBuildingMeetsAllCurrentLocalStateAndCountryBuildingCodes otamodel.EnumString = "Building meets all current local, state and country building codes"
	SecurityFeatureCarbonMonoxideDetector                                   otamodel.EnumString = "Carbon monoxide detector"
	SecurityFeatureCompliesWithLocalStateFederalFireLaws                    otamodel.EnumString = "Complies with Local/State/Federal fire laws"
	SecurityFeatureConnectingDoorsHaveDeadbolts                             otamodel.EnumString = "Connecting doors have deadbolts"
	SecurityFeatureDeadBoltsOnGuestRoomDoors                                otamodel.EnumString = "Dead bolts on guest room doors"
	SecurityFeatureElectronicRoomKey                                        otamodel.EnumString = "Electronic room key"
	SecurityFeatureElevatorAutoRecall                                       otamodel.EnumString = "Elevator auto recall"
	SecurityFeatureEmergencyBackUpGenerators                                otamodel.EnumString = "Emergency back-up generators"
	SecurityFeatureEmergencyEvacuationPlan                                  otamodel.EnumString = "Emergency evacuation plan"
	SecurityFeatureEmergencyExitsOnEachFloor                                otamodel.EnumString = "Emergency exits on each floor"
	SecurityFeatureEmergencyInfoInRoom                                      otamodel.EnumString = "Emergency info in room"
	SecurityFeatureEmergencyLighting                                        otamodel.EnumString = "Emergency lighting"
	SecurityFeatureEvacuationDrills                                         otamodel.EnumString = "Evacuation drills"
	SecurityFeatureExteriorDoorsExceptLobbyEntranceRequireKeyAccessAtNight  otamodel.EnumString = "Exterior doors (except lobby entrance) require key access at night"
	SecurityFeatureFEMAApproved                                             otamodel.EnumString = "FEMA approved"
	SecurityFeatureFireExtinguishers                                        otamodel.EnumString = "Fire extinguishers"
	SecurityFeatureFireExtinguishersInHallways                              otamodel.EnumString = "Fire extinguishers in hallways"
	SecurityFeatureFireExtinguishersInPublicAreas                           otamodel.EnumString = "Fire extinguishers in public areas"
	SecurityFeatureFirstAidAvailable                                        otamodel.EnumString = "First aid available"
	SecurityFeatureGuestRoomDoorsSelfClosing                                otamodel.EnumString = "Guest room doors self-closing"
	SecurityFeatureHardWiredSmokeDetectors                                  otamodel.EnumString = "Hard wired smoke detectors"
	SecurityFeatureHealthClubFacilitiesPoolGymRequireKeyAccessForEntrance   otamodel.EnumString = "Health club facilities (pool/gym) require key access for entrance"
	SecurityFeatureHoursSecurity                                            otamodel.EnumString = "Hours security"
	SecurityFeatureIfNo24HourSecurityWhatAreTheHours                        otamodel.EnumString = "If no 24 hour security, what are the hours?"
	SecurityFeatureLightedParkingArea                                       otamodel.EnumString = "Lighted parking area"
	SecurityFeatureMultipleExitsOnEachFloor                                 otamodel.EnumString = "Multiple exits on each floor"
	SecurityFeaturePatrolledParkingArea                                     otamodel.EnumString = "Patrolled parking area"
	SecurityFeaturePrivateSecurityAvailable                                 otamodel.EnumString = "Private security available"
	SecurityFeaturePropertyHasElevators                                     otamodel.EnumString = "Property has elevators"
	SecurityFeaturePublicAddressSystem                                      otamodel.EnumString = "Public address system"
	SecurityFeatureRoomAccessThroughExteriorCorridor                        otamodel.EnumString = "Room access through exterior corridor"
	SecurityFeatureRoomAccessThroughInteriorCorridor                        otamodel.EnumString = "Room access through interior corridor"
	SecurityFeatureRoomAccessibleThroughBalconySlidingGlassDoors            otamodel.EnumString = "Room accessible through balcony sliding glass doors"
	SecurityFeatureRoomWindowsOpen                                          otamodel.EnumString = "Room windows open"
	SecurityFeatureSafetyChainsOnGuestDoors                                 otamodel.EnumString = "Safety chains on guest doors"
	SecurityFeatureSecondaryLocksOnRoomWindows                              otamodel.EnumString = "Secondary locks on room windows"
	SecurityFeatureSecondaryLocksOnSlidingGlassDoors                        otamodel.EnumString = "Secondary locks on sliding glass doors"
	SecurityFeatureSecuredFloors                                            otamodel.EnumString = "Secured floors"
	SecurityFeatureSecurity                                                 otamodel.EnumString = "Security"
	SecurityFeatureSecurity24HoursDay                                       otamodel.EnumString = "Security 24 hours/day"
	SecurityFeatureSecurityEscortsAvailableOnRequest                        otamodel.EnumString = "Security escorts available on request"
	SecurityFeatureOther                                                    otamodel.EnumString = "Other_"
	SecurityFeatureSmokeDetectorInGuestRooms                                otamodel.EnumString = "Smoke detector in guest rooms"
	SecurityFeatureSmokeDetectorInHallways                                  otamodel.EnumString = "Smoke detector in hallways"
	SecurityFeatureSmokeDetectorInPublicAreas                               otamodel.EnumString = "Smoke detector in public areas"
	SecurityFeatureSprinklersInGuestRooms                                   otamodel.EnumString = "Sprinklers in guest rooms"
	SecurityFeatureSprinklersInHallways                                     otamodel.EnumString = "Sprinklers in hallways"
	SecurityFeatureSprinklersInPublicAreas                                  otamodel.EnumString = "Sprinklers in public areas"
	SecurityFeatureStaffRedCrossCertifiedInCPR                              otamodel.EnumString = "Staff Red Cross certified in CPR"
	SecurityFeatureStaffTrainedInAutomatedExternalDefibrillatorAEDUsage     otamodel.EnumString = "Staff trained in Automated External Defibrillator (AED) usage"
	SecurityFeatureStaffTrainedInCPR                                        otamodel.EnumString = "Staff trained in CPR"
	SecurityFeatureStaffTrainedInDuplicateKeyIssue                          otamodel.EnumString = "Staff trained in duplicate key issue"
	SecurityFeatureStaffTrainedInFirstAid                                   otamodel.EnumString = "Staff trained in first aid"
	SecurityFeatureSwingboltLock                                            otamodel.EnumString = "Swingbolt lock"
	SecurityFeatureThe2NdLockOnGuestDoors                                   otamodel.EnumString = "2nd lock on guest doors"
	SecurityFeatureVIPSecurity                                              otamodel.EnumString = "VIP Security"
	SecurityFeatureVentilatedStairWells                                     otamodel.EnumString = "Ventilated stair wells"
	SecurityFeatureVideoCamerasAtEntrance                                   otamodel.EnumString = "Video cameras at entrance"
	SecurityFeatureVideoCamerasInPublicAreas                                otamodel.EnumString = "Video cameras in public areas"
	SecurityFeatureVideoSurveillanceMonitored24HrsADay                      otamodel.EnumString = "Video surveillance monitored 24 hrs a day"
	SecurityFeatureVideoSurveillanceOfParking                               otamodel.EnumString = "Video surveillance of parking"
	SecurityFeatureVideoSurveillanceRecorded24HrsADay                       otamodel.EnumString = "Video surveillance recorded 24 hrs a day"
	SecurityFeatureViewportsInGuestRoomDoors                                otamodel.EnumString = "Viewports in guest room doors"
	SecurityFeatureVisualAlarmInGuestRooms                                  otamodel.EnumString = "Visual alarm in guest rooms"
	SecurityFeatureVisualAlarmsInHallways                                   otamodel.EnumString = "Visual alarms in hallways"
	SecurityFeatureVisualAlarmsInPublicAreas                                otamodel.EnumString = "Visual alarms in public areas"
)

// AgeQualifyingCode A code representing a business rule that determines the charges for a guest based upon
// age range (e.g. Adult, Child, Senior, Child With Adult, Child Without Adult). This
// attribute allows for an increase in rate by occupant class.\nPerson age
// categories.\nNote: Age categories  are typically used to qualify pricing and\/or
// eligibility.
const (
	AgeQualifyingCodeAdditionalOccupantWithAdult    otamodel.EnumString = "Additional occupant with adult"
	AgeQualifyingCodeAdditionalOccupantWithoutAdult otamodel.EnumString = "Additional occupant without adult"
	AgeQualifyingCodeAdult                          otamodel.EnumString = "Adult"
	AgeQualifyingCodeOther                          otamodel.EnumString = "Other_"
	AgeQualifyingCodeChild                          otamodel.EnumString = "Child"
	AgeQualifyingCodeFreeAdult                      otamodel.EnumString = "Free adult"
	AgeQualifyingCodeFreeChild                      otamodel.EnumString = "Free child"
	AgeQualifyingCodeInfant                         otamodel.EnumString = "Infant"
	AgeQualifyingCodeJunior                         otamodel.EnumString = "Junior"
	AgeQualifyingCodeOver21                         otamodel.EnumString = "Over 21"
	AgeQualifyingCodeOver65                         otamodel.EnumString = "Over 65"
	AgeQualifyingCodeSenior                         otamodel.EnumString = "Senior"
	AgeQualifyingCodeTeenager                       otamodel.EnumString = "Teenager"
	AgeQualifyingCodeUnder10                        otamodel.EnumString = "Under 10"
	AgeQualifyingCodeUnder12                        otamodel.EnumString = "Under 12"
	AgeQualifyingCodeUnder17                        otamodel.EnumString = "Under 17"
	AgeQualifyingCodeUnder2                         otamodel.EnumString = "Under 2"
	AgeQualifyingCodeUnder21                        otamodel.EnumString = "Under 21"
	AgeQualifyingCodeYoungDriver                    otamodel.EnumString = "Young driver"
	AgeQualifyingCodeYoungerDriver                  otamodel.EnumString = "Younger driver"
)

// BedType The type(s) of sleeping option(s) in a guest accommodation.
const (
	BedTypeOther         otamodel.EnumString = "Other_"
	BedTypeRunOfTheHouse otamodel.EnumString = "Run of the house"
	BedTypeDormBed       otamodel.EnumString = "Dorm bed"
	BedTypeDoubleFull    otamodel.EnumString = "Double/full"
	BedTypeFuton         otamodel.EnumString = "Futon"
	BedTypeKing          otamodel.EnumString = "King"
	BedTypeMurphyBed     otamodel.EnumString = "Murphy bed"
	BedTypeQueen         otamodel.EnumString = "Queen"
	BedTypeSofaBed       otamodel.EnumString = "Sofa bed"
	BedTypeTatamiMats    otamodel.EnumString = "Tatami mats"
	BedTypeTwinSingle    otamodel.EnumString = "Twin/single"
	BedTypeWaterBed      otamodel.EnumString = "Water bed"
)

// ProximityEnumBase Specifies if the item in question is onsite, offsite, nearby, etc.
const (
	ProximityInformationNotAvailable otamodel.EnumString = "Information not available"
	ProximityNearby                  otamodel.EnumString = "Nearby"
	ProximityOffsite                 otamodel.EnumString = "Offsite"
	ProximityOnsite                  otamodel.EnumString = "Onsite"
	ProximityOnsiteAndOffsite        otamodel.EnumString = "Onsite and offsite"
	ProximityOther                   otamodel.EnumString = "Other_"
)

// SegmentCategoryEnumBase Describes the segment type.
const (
	SegmentCategoryBudget            otamodel.EnumString = "Budget"
	SegmentCategoryFirstClass        otamodel.EnumString = "First Class"
	SegmentCategoryMidscale          otamodel.EnumString = "Midscale"
	SegmentCategoryMidscaleWithoutFB otamodel.EnumString = "Midscale without F&B"
	SegmentCategoryModerate          otamodel.EnumString = "Moderate"
	SegmentCategoryQuality           otamodel.EnumString = "Quality"
	SegmentCategoryDeluxe            otamodel.EnumString = "Deluxe"
	SegmentCategoryEconomy           otamodel.EnumString = "Economy"
	SegmentCategoryLuxury            otamodel.EnumString = "Luxury"
	SegmentCategoryOther             otamodel.EnumString = "Other_"
	SegmentCategoryStandard          otamodel.EnumString = "Standard"
	SegmentCategoryTourist           otamodel.EnumString = "Tourist"
	SegmentCategoryUpperUpscale      otamodel.EnumString = "Upper upscale"
	SegmentCategoryUpscale           otamodel.EnumString = "Upscale"
)

// GuestRoomInfo Identifies a property's accommodation\/inventory types for which it is useful to specify
// a property-level count or availability status.
const (
	GuestRoomInfoAccommodationsWithBalcony     otamodel.EnumString = "Accommodations with balcony"
	GuestRoomInfoAdjoiningRoomsOrSuites        otamodel.EnumString = "Adjoining rooms or suites"
	GuestRoomInfoApartments                    otamodel.EnumString = "Apartments"
	GuestRoomInfoAvailableRooms                otamodel.EnumString = "Available rooms"
	GuestRoomInfoAvailableSuites               otamodel.EnumString = "Available suites"
	GuestRoomInfoBuildings                     otamodel.EnumString = "Buildings"
	GuestRoomInfoBungalow                      otamodel.EnumString = "Bungalow"
	GuestRoomInfoBusinessClass                 otamodel.EnumString = "Business class"
	GuestRoomInfoBusinessPlan                  otamodel.EnumString = "Business plan"
	GuestRoomInfoCabin                         otamodel.EnumString = "Cabin"
	GuestRoomInfoClassic                       otamodel.EnumString = "Classic"
	GuestRoomInfoClubLevels                    otamodel.EnumString = "Club levels"
	GuestRoomInfoComfort                       otamodel.EnumString = "Comfort"
	GuestRoomInfoConciergeLevels               otamodel.EnumString = "Concierge levels"
	GuestRoomInfoCondos                        otamodel.EnumString = "Condos"
	GuestRoomInfoConnectingRoomsOrSuites       otamodel.EnumString = "Connecting rooms or suites"
	GuestRoomInfoCottage                       otamodel.EnumString = "Cottage"
	GuestRoomInfoDeluxeSuite                   otamodel.EnumString = "Deluxe suite"
	GuestRoomInfoDoubleBedrooms                otamodel.EnumString = "Double bedrooms"
	GuestRoomInfoDoubleDoubleBedrooms          otamodel.EnumString = "Double double bedrooms"
	GuestRoomInfoDriveUpRooms                  otamodel.EnumString = "Drive up rooms"
	GuestRoomInfoEffeciency                    otamodel.EnumString = "Effeciency"
	GuestRoomInfoFamilyOversizedAccommodations otamodel.EnumString = "Family/oversized accommodations"
	GuestRoomInfoFirstFloorRooms               otamodel.EnumString = "First floor rooms"
	GuestRoomInfoFloors                        otamodel.EnumString = "Floors"
	GuestRoomInfoAccessibleRooms               otamodel.EnumString = "Accessible rooms"
	GuestRoomInfoDeluxe                        otamodel.EnumString = "Deluxe"
	GuestRoomInfoEconomy                       otamodel.EnumString = "Economy"
	GuestRoomInfoExecutiveFloor                otamodel.EnumString = "Executive floor"
	GuestRoomInfoLuxury                        otamodel.EnumString = "Luxury"
	GuestRoomInfoOther                         otamodel.EnumString = "Other_"
	GuestRoomInfoRoom                          otamodel.EnumString = "Room"
	GuestRoomInfoRunOfTheHouse                 otamodel.EnumString = "Run of the house"
	GuestRoomInfoStandard                      otamodel.EnumString = "Standard"
	GuestRoomInfoJacuzziSuite                  otamodel.EnumString = "Jacuzzi Suite"
	GuestRoomInfoJuniorSuite                   otamodel.EnumString = "Junior suite"
	GuestRoomInfoKingBedrooms                  otamodel.EnumString = "King bedrooms"
	GuestRoomInfoKingKingBedrooms              otamodel.EnumString = "King king bedrooms"
	GuestRoomInfoLanai                         otamodel.EnumString = "Lanai"
	GuestRoomInfoLargeSuite                    otamodel.EnumString = "Large suite"
	GuestRoomInfoLoft                          otamodel.EnumString = "Loft"
	GuestRoomInfoNonsmokingRooms               otamodel.EnumString = "Nonsmoking rooms"
	GuestRoomInfoParlour                       otamodel.EnumString = "Parlour"
	GuestRoomInfoPenthouses                    otamodel.EnumString = "Penthouses"
	GuestRoomInfoPremier                       otamodel.EnumString = "Premier"
	GuestRoomInfoQueenBedrooms                 otamodel.EnumString = "Queen bedrooms"
	GuestRoomInfoQueenQueenBedrooms            otamodel.EnumString = "Queen queen bedrooms"
	GuestRoomInfoSeparateFloorsForWomen        otamodel.EnumString = "Separate floors for women"
	GuestRoomInfoSmokingRooms                  otamodel.EnumString = "Smoking rooms"
	GuestRoomInfoStudios                       otamodel.EnumString = "Studios"
	GuestRoomInfoSuites                        otamodel.EnumString = "Suites"
	GuestRoomInfoSuperior                      otamodel.EnumString = "Superior"
	GuestRoomInfoThe1RoomCabin                 otamodel.EnumString = "1 room cabin"
	GuestRoomInfoTotalAvailableRoomsAndSuites  otamodel.EnumString = "Total available rooms and suites"
	GuestRoomInfoTotalRooms                    otamodel.EnumString = "Total rooms"
	GuestRoomInfoTwinBedrooms                  otamodel.EnumString = "Twin bedrooms"
	GuestRoomInfoTwinTwinBedrooms              otamodel.EnumString = "Twin twin bedrooms"
	GuestRoomInfoVilla                         otamodel.EnumString = "Villa"
)

// otamodel.EnumString Specifies information about a facility, amenity or service that is relevant to people
// with a disability.
const (
	DisabilityFeatureAccessibilityToGoodsAndServices                                 otamodel.EnumString = "Accessibility to goods and services"
	DisabilityFeatureAccessibleBaths                                                 otamodel.EnumString = "Accessible baths"
	DisabilityFeatureAccessibleEntrance                                              otamodel.EnumString = "Accessible entrance"
	DisabilityFeatureAccessibleParking                                               otamodel.EnumString = "Accessible parking"
	DisabilityFeatureAccessiblePlatformLiftsAvailable                                otamodel.EnumString = "Accessible platform lifts available"
	DisabilityFeatureAccessibleSelfParkingAvailable                                  otamodel.EnumString = "Accessible self parking available"
	DisabilityFeatureAccessibleVanParking                                            otamodel.EnumString = "Accessible van parking"
	DisabilityFeatureAccommodationsHaveBathInBedroom                                 otamodel.EnumString = "Accommodations have bath in bedroom"
	DisabilityFeatureAdaptedRoomDoors                                                otamodel.EnumString = "Adapted room doors"
	DisabilityFeatureAdjustableHeightHandHeldShowerWand                              otamodel.EnumString = "Adjustable height hand-held shower wand"
	DisabilityFeatureAmericansWithDisabilitiesActADACompliance                       otamodel.EnumString = "Americans with Disabilities Act (ADA) compliance"
	DisabilityFeatureAssistiveListeningDevicesForMeetingsUponRequest                 otamodel.EnumString = "Assistive listening devices for meetings upon request"
	DisabilityFeatureAudibleEmergencyAlarmForSightImpairedGuest                      otamodel.EnumString = "Audible emergency alarm for sight impaired guest"
	DisabilityFeatureBathroomDoorsInInches                                           otamodel.EnumString = "Bathroom doors in inches"
	DisabilityFeatureBathroomDoorsOpenOutwards                                       otamodel.EnumString = "Bathroom doors open outwards"
	DisabilityFeatureBathroomVanityInGuestRoomsForWheelchairUserSHeight              otamodel.EnumString = "Bathroom vanity in guest rooms for wheelchair user's height"
	DisabilityFeatureBathtubGrabBars                                                 otamodel.EnumString = "Bathtub grab bars"
	DisabilityFeatureBathtubSeat                                                     otamodel.EnumString = "Bathtub seat"
	DisabilityFeatureBedTypesOfWheelchairAccessibleRooms                             otamodel.EnumString = "Bed types of wheelchair accessible rooms"
	DisabilityFeatureBedroomWheelchairAccess                                         otamodel.EnumString = "Bedroom wheelchair access"
	DisabilityFeatureBenchesInLockerRooms                                            otamodel.EnumString = "Benches in locker rooms."
	DisabilityFeatureBrailleLargePrintLiterature                                     otamodel.EnumString = "Braille/large print literature"
	DisabilityFeatureBrailleSignageProvided                                          otamodel.EnumString = "Braille signage provided"
	DisabilityFeatureBusinessCenter                                                  otamodel.EnumString = "Business center"
	DisabilityFeatureClosedCaptionTV                                                 otamodel.EnumString = "Closed caption TV"
	DisabilityFeatureClosetRodsInGuestRoomsForDisabledPersonHeight                   otamodel.EnumString = "Closet rods in guest rooms for disabled person height"
	DisabilityFeatureComplementaryAccessibleTransportationWithAdvancedNotice         otamodel.EnumString = "Complementary accessible transportation with advanced notice"
	DisabilityFeatureCompliesWithLocalStateFederalLawsForDisabled                    otamodel.EnumString = "Complies with Local/State/Federal laws for disabled"
	DisabilityFeatureConciergeDeskIsWheelchairAccessible                             otamodel.EnumString = "Concierge desk is wheelchair accessible"
	DisabilityFeatureDescribeInDetailHowYourKitchenIsAccessible                      otamodel.EnumString = "Describe in detail how your kitchen is accessible."
	DisabilityFeatureAccessibleRooms                                                 otamodel.EnumString = "Accessible rooms"
	DisabilityFeatureOther                                                           otamodel.EnumString = "Other_"
	DisabilityFeatureDoesHotelHaveAccessibleParking                                  otamodel.EnumString = "Does hotel have accessible parking?"
	DisabilityFeatureDoorWidthInInches                                               otamodel.EnumString = "Door width in inches"
	DisabilityFeatureDrinkingFountainsAccessible                                     otamodel.EnumString = "Drinking fountains accessible"
	DisabilityFeatureElevatorAccessToAllLevels                                       otamodel.EnumString = "Elevator access to all levels"
	DisabilityFeatureElevatorNearAccessibleRooms                                     otamodel.EnumString = "Elevator near accessible rooms"
	DisabilityFeatureElevatorsEquippedForAccessibility                               otamodel.EnumString = "Elevators equipped for accessibility"
	DisabilityFeatureElevatorsHaveBrailleInstructions                                otamodel.EnumString = "Elevators have Braille Instructions"
	DisabilityFeatureEmergencyCordButtonSystemInBathroom                             otamodel.EnumString = "Emergency cord/button system in bathroom"
	DisabilityFeatureEmergencyCordButtonSystemInBedroom                              otamodel.EnumString = "Emergency cord/button system in bedroom"
	DisabilityFeatureEmergencyExitSignsInBraille                                     otamodel.EnumString = "Emergency exit signs in Braille"
	DisabilityFeatureEmergencyInfoInBraille                                          otamodel.EnumString = "Emergency info in Braille"
	DisabilityFeatureEmergencyInstructionsInPictorialForm                            otamodel.EnumString = "Emergency instructions in pictorial form"
	DisabilityFeatureEmergenyProceduresForPeopleWithDisabilites                      otamodel.EnumString = "Emergeny procedures for people with disabilites"
	DisabilityFeatureExerciseFacilityIsWheelchairAccessible                          otamodel.EnumString = "Exercise facility is wheelchair accessible"
	DisabilityFeatureFacilitiesForPeopleWithHearingImpairmentOnly                    otamodel.EnumString = "Facilities for people with hearing impairment only"
	DisabilityFeatureFacilitiesForPeopleWithVisionImpairmentOnly                     otamodel.EnumString = "Facilities for people with vision impairment only"
	DisabilityFeatureFeatherFreeBeddingPillowsAvailable                              otamodel.EnumString = "Feather free bedding/pillows available"
	DisabilityFeatureFlashingDoorKnockerAvailable                                    otamodel.EnumString = "Flashing door knocker available"
	DisabilityFeatureFlatTerrainBetweenParkingAndEntrance                            otamodel.EnumString = "Flat terrain between parking and entrance"
	DisabilityFeatureFoodServiceLinesAccessible                                      otamodel.EnumString = "Food service lines accessible"
	DisabilityFeatureGrabBarsInBathroom                                              otamodel.EnumString = "Grab bars in bathroom"
	DisabilityFeatureGuestRoomsAndAccessRoutesAreAccessible                          otamodel.EnumString = "Guest rooms and access routes are accessible"
	DisabilityFeatureHearingImpairedServices                                         otamodel.EnumString = "Hearing impaired services"
	DisabilityFeatureHearingInductionLoopSystemInstalled                             otamodel.EnumString = "Hearing induction loop system installed"
	DisabilityFeatureHeightFromGroundOfDeadboltInGuestRoom                           otamodel.EnumString = "Height from ground of deadbolt in guest room"
	DisabilityFeatureHeightFromGroundOfElevatorExternalButtons                       otamodel.EnumString = "Height from ground of elevator external buttons"
	DisabilityFeatureHeightFromGroundOfElevatorInternalButtons                       otamodel.EnumString = "Height from ground of elevator internal buttons"
	DisabilityFeatureHeightFromGroundOfElevatorInternalHandrails                     otamodel.EnumString = "Height from ground of elevator internal handrails"
	DisabilityFeatureHeightFromGroundOfGuestBedIncludingMattress                     otamodel.EnumString = "Height from ground of guest bed including mattress"
	DisabilityFeatureHeightFromGroundOfThermostatInGuestRoom                         otamodel.EnumString = "Height from ground of thermostat in guest room"
	DisabilityFeatureHeightFromGroundToLightSwitchesInBathroom                       otamodel.EnumString = "Height from ground to light switches in bathroom"
	DisabilityFeatureHeightFromGroundToLightSwitchesInGuestRoom                      otamodel.EnumString = "Height from ground to light switches in guest room"
	DisabilityFeatureHeightFromGroundToPeepholeInGuestRoomDoor                       otamodel.EnumString = "Height from ground to peephole in guest room door"
	DisabilityFeatureHeightOfBathroomBasin                                           otamodel.EnumString = "Height of bathroom basin"
	DisabilityFeatureHeightOfBathroomToiletSeat                                      otamodel.EnumString = "Height of bathroom toilet seat"
	DisabilityFeatureHeightOfControlsAtHighestOperablePartForBath                    otamodel.EnumString = "Height of controls at highest operable part for bath"
	DisabilityFeatureHeightOfControlsAtHighestOperablePartForRollInShower            otamodel.EnumString = "Height of controls at highest operable part for roll-in shower"
	DisabilityFeatureHeightOfDeadboltInGuestRoomInFeet                               otamodel.EnumString = "Height of deadbolt in guest room (in feet)"
	DisabilityFeatureHeightOfDeadboltInGuestRoomInInches                             otamodel.EnumString = "Height of deadbolt in guest room (in Inches)"
	DisabilityFeatureHeightOfLightSwitchesInGuestRoomsFeet                           otamodel.EnumString = "Height of light switches in guest rooms (feet)"
	DisabilityFeatureHeightOfLightSwitchesInGuestRoomsInches                         otamodel.EnumString = "Height of light switches in guest rooms (inches)"
	DisabilityFeatureHeightOfNonSlipHandrailsAdjacentToBath                          otamodel.EnumString = "Height of non-slip handrails adjacent to bath"
	DisabilityFeatureHeightOfNonSlipHandrailsAdjacentToBathroomToilet                otamodel.EnumString = "Height of non-slip handrails adjacent to bathroom toilet"
	DisabilityFeatureHeightOfNonSlipHandrailsInShowerArea                            otamodel.EnumString = "Height of non-slip handrails in shower area"
	DisabilityFeatureHeightOfPeepholeInGuestRoomInFeet                               otamodel.EnumString = "Height of peephole in guest room (in feet)"
	DisabilityFeatureHeightOfPeepholeInGuestRoomInInches                             otamodel.EnumString = "Height of peephole in guest room (in inches)"
	DisabilityFeatureHeightOfThermostatInGuestRoomInFeet                             otamodel.EnumString = "Height of thermostat in guest room (in feet)"
	DisabilityFeatureHeightOfThermostatInGuestRoomInInches                           otamodel.EnumString = "Height of thermostat in guest room (in inches)"
	DisabilityFeatureHotelEntranceIsAccessible                                       otamodel.EnumString = "Hotel entrance is accessible"
	DisabilityFeatureHotelRestaurantIsWheelchairAccessible                           otamodel.EnumString = "Hotel restaurant is wheelchair accessible"
	DisabilityFeatureImpairmentAidsAvailable                                         otamodel.EnumString = "Impairment aids available"
	DisabilityFeatureLengthDepthOfClearFloorSpaceInFrontOfBath                       otamodel.EnumString = "Length/depth of clear floor space in front of bath"
	DisabilityFeatureLengthDepthOfClearFloorSpaceInFrontOfGuestBathroomToilet        otamodel.EnumString = "Length/depth of clear floor space in front of guest bathroom toilet"
	DisabilityFeatureLeverHandlesOnGuestRoomDoors                                    otamodel.EnumString = "Lever handles on guest room doors"
	DisabilityFeatureLightSwitchesInGuestRoomsForWheelchairUserSHeight               otamodel.EnumString = "Light switches in guest rooms for wheelchair user's height"
	DisabilityFeatureListAvailableRoomTypesForDisabledPersons8Fields                 otamodel.EnumString = "List available room types for disabled persons- 8 fields"
	DisabilityFeatureLockerRoomsAccessible                                           otamodel.EnumString = "Locker rooms accessible"
	DisabilityFeatureLowerLevelSeatingRequired                                       otamodel.EnumString = "Lower level seating required"
	DisabilityFeatureLoweredElectricalOutlets                                        otamodel.EnumString = "Lowered electrical outlets"
	DisabilityFeatureLoweredNightGuardsOnGuestRoomDoors                              otamodel.EnumString = "Lowered night guards on guest room doors"
	DisabilityFeatureNumberOfAccessibleMeetingRooms                                  otamodel.EnumString = "Number of accessible meeting rooms"
	DisabilityFeatureNumberOfAccessibleRoomsWithStandardTub                          otamodel.EnumString = "Number of accessible rooms with standard tub"
	DisabilityFeatureNumberOfEachRoomTypeEquippedForDisabledPersons8Fields           otamodel.EnumString = "Number of each room type equipped for disabled persons- 8 fields"
	DisabilityFeatureNumberOfRollInShowersAvailable                                  otamodel.EnumString = "Number of roll-in showers available"
	DisabilityFeatureNumberOfRoomsWithBraille                                        otamodel.EnumString = "Number of rooms with Braille"
	DisabilityFeatureNumberOfRoomsWithWheelchairAccessibleShowers                    otamodel.EnumString = "Number of rooms with wheelchair accessible showers"
	DisabilityFeatureNumberOfWheelchairAccessibleRooms                               otamodel.EnumString = "Number of wheelchair accessible rooms"
	DisabilityFeatureOtherServicesForPersonsWithDisabilities                         otamodel.EnumString = "Other services for persons with disabilities"
	DisabilityFeaturePassengerHasMeetAndAssistRequirement                            otamodel.EnumString = "Passenger has meet and assist requirement"
	DisabilityFeaturePassengerHasOxygenEquipment                                     otamodel.EnumString = "Passenger has oxygen equipment"
	DisabilityFeaturePoolIsWheelchairAccessible                                      otamodel.EnumString = "Pool is wheelchair accessible"
	DisabilityFeaturePortableBathtubSeats                                            otamodel.EnumString = "Portable bathtub seats"
	DisabilityFeaturePublicAreasWheelchairAccessible                                 otamodel.EnumString = "Public areas wheelchair accessible"
	DisabilityFeaturePublicTelephonesAccessible                                      otamodel.EnumString = "Public telephones accessible"
	DisabilityFeatureRaisedToiletSeatWithGrabBars                                    otamodel.EnumString = "Raised toilet seat with grab bars"
	DisabilityFeatureRampAccess                                                      otamodel.EnumString = "Ramp access"
	DisabilityFeatureRegistrationDeskIsWheelchairAccessible                          otamodel.EnumString = "Registration desk is wheelchair accessible"
	DisabilityFeatureRestaurantBarMenusAvailableIn14PtPrint                          otamodel.EnumString = "Restaurant/bar menus available in 14pt print"
	DisabilityFeatureRestaurantBarMenusAvailableInBraille                            otamodel.EnumString = "Restaurant/bar menus available in Braille"
	DisabilityFeatureRestroomFacilitiesAccessible                                    otamodel.EnumString = "Restroom facilities accessible"
	DisabilityFeatureRollInShowerAreaWithBathroomSeat                                otamodel.EnumString = "Roll-in shower area with bathroom seat"
	DisabilityFeatureRollInShowerAvailable                                           otamodel.EnumString = "Roll-in shower available"
	DisabilityFeatureRouteFromAccessiblePublicEntranceToBusinessCenterIsAccessible   otamodel.EnumString = "Route from accessible public entrance to business center is accessible"
	DisabilityFeatureRouteFromAccessiblePublicEntranceToExerciseFacilityIsAccessible otamodel.EnumString = "Route from accessible public entrance to exercise facility is accessible"
	DisabilityFeatureRouteFromAccessiblePublicEntranceToMeetingRoomsIsAccessible     otamodel.EnumString = "Route from accessible public entrance to meeting rooms is accessible"
	DisabilityFeatureRouteFromAccessiblePublicEntranceToPoolIsAccessible             otamodel.EnumString = "Route from accessible public entrance to pool is accessible"
	DisabilityFeatureRouteFromAccessiblePublicEntranceToRegistrationAreaIsAccessible otamodel.EnumString = "Route from accessible public entrance to registration area is accessible"
	DisabilityFeatureRouteFromAccessiblePublicEntranceToRestaurantIsAccessible       otamodel.EnumString = "Route from accessible public entrance to restaurant is accessible"
	DisabilityFeatureRouteFromAccessiblePublicEntranceToSPAIsAccessible              otamodel.EnumString = "Route from accessible public entrance to spa is accessible"
	DisabilityFeatureSafetyBarsInShower                                              otamodel.EnumString = "Safety bars in shower"
	DisabilityFeatureSalesAndServiceCountersAccessible                               otamodel.EnumString = "Sales and service counters accessible"
	DisabilityFeatureServiceAnimalsAllowedOnPropertyForPeopleWithDisabilities        otamodel.EnumString = "Service animals allowed on property for people with disabilities"
	DisabilityFeatureServiceDogsAllowed                                              otamodel.EnumString = "Service dogs allowed"
	DisabilityFeatureSpecialNeedsMenus                                               otamodel.EnumString = "Special needs menus"
	DisabilityFeatureStaffProficientInSignLanguage                                   otamodel.EnumString = "Staff proficient in sign language"
	DisabilityFeatureStaffTrainedInServiceToDisabledGuests                           otamodel.EnumString = "Staff trained in service to disabled guests"
	DisabilityFeatureStepsStaircasesHaveColorMarkings                                otamodel.EnumString = "Steps/staircases have color markings"
	DisabilityFeatureStepsStaircasesHaveHandrails                                    otamodel.EnumString = "Steps/staircases have handrails"
	DisabilityFeatureSubtitlesClosedCaptionsAvailableOnTV                            otamodel.EnumString = "Subtitles/closed captions available on TV"
	DisabilityFeatureTTYTTDCompatible                                                otamodel.EnumString = "TTY/TTD compatible"
	DisabilityFeatureTactile14PtPrintSignageThroughoutHotel                          otamodel.EnumString = "Tactile/14pt print signage throughout hotel"
	DisabilityFeatureTelephoneForHearingImpaired                                     otamodel.EnumString = "Telephone for hearing impaired"
	DisabilityFeatureTelevisionAmplifier                                             otamodel.EnumString = "Television amplifier"
	DisabilityFeatureToiletSeatInGuestRoomsForDisabledPerson                         otamodel.EnumString = "Toilet seat in guest rooms for disabled person"
	DisabilityFeatureValetParkingAcceptsAndParksVehiclesOutfittedForWheelchairUsers  otamodel.EnumString = "Valet parking accepts and parks vehicles outfitted for wheelchair users"
	DisabilityFeatureVanAccessibleParkingInSelfParking                               otamodel.EnumString = "Van accessible parking in self parking"
	DisabilityFeatureViabratingAlarmAvailable                                        otamodel.EnumString = "Viabrating alarm available"
	DisabilityFeatureVibratingPillowsAvailable                                       otamodel.EnumString = "Vibrating pillows available"
	DisabilityFeatureVisualEmergencyAlarmForHearingImpairedGuest                     otamodel.EnumString = "Visual emergency alarm for hearing impaired guest"
	DisabilityFeatureWalkInShower                                                    otamodel.EnumString = "Walk-in shower"
	DisabilityFeatureWhatRoomTypesHaveWheelInShowersFreeFormStringbox                otamodel.EnumString = "What room types have wheel-in showers? (free form stringbox)"
	DisabilityFeatureWheelchairAccessibleElevators                                   otamodel.EnumString = "Wheelchair accessible elevators"
	DisabilityFeatureWheelchairLiftRequired                                          otamodel.EnumString = "Wheelchair lift required"
	DisabilityFeatureWheelchairPassengerHasOwnChairBuses                             otamodel.EnumString = "Wheelchair, passenger has own chair, buses"
	DisabilityFeatureWheelchairPassengerHasOwnChairTrains                            otamodel.EnumString = "Wheelchair, passenger has own chair, trains"
	DisabilityFeatureWheelchairPassengerRequiresStationWheelchair                    otamodel.EnumString = "Wheelchair, passenger requires station wheelchair"
	DisabilityFeatureWheelchairsAvailable                                            otamodel.EnumString = "Wheelchairs available"
	DisabilityFeatureWhichFloorsHaveAccessibleRooms                                  otamodel.EnumString = "Which floors have accessible rooms"
	DisabilityFeatureWideCorridors                                                   otamodel.EnumString = "Wide corridors"
	DisabilityFeatureWideEntrance                                                    otamodel.EnumString = "Wide entrance"
	DisabilityFeatureWideRestaurantEntrance                                          otamodel.EnumString = "Wide restaurant entrance"
	DisabilityFeatureWidthDiameterOfClearFloorSpaceAtMainHotelEntrance               otamodel.EnumString = "Width/diameter of clear floor space at main hotel entrance"
	DisabilityFeatureWidthDiameterOfClearFloorSpaceAtMainRestaurantEntrance          otamodel.EnumString = "Width/diameter of clear floor space at main restaurant entrance"
	DisabilityFeatureWidthDiameterOfClearFloorSpaceInFrontOfBath                     otamodel.EnumString = "Width/diameter of clear floor space in front of bath"
	DisabilityFeatureWidthDiameterOfClearFloorSpaceInFrontOfGuestBathroomToilet      otamodel.EnumString = "Width/diameter of clear floor space in front of guest bathroom toilet"
	DisabilityFeatureWidthDiameterOfClearOpeningSpaceAtBathroomDoor                  otamodel.EnumString = "Width/diameter of clear opening space at bathroom door"
	DisabilityFeatureWidthDiameterOfClearOpeningSpaceAtBedroomDoor                   otamodel.EnumString = "Width/diameter of clear opening space at bedroom door"
	DisabilityFeatureWidthDiameterOfElevatorClearDoorOpeningSpace                    otamodel.EnumString = "Width/diameter of elevator clear door opening space"
	DisabilityFeatureWidthDiameterOfMainCorridors                                    otamodel.EnumString = "Width/diameter of main corridors"
	DisabilityFeatureWidthDiameterOfWheelchairTurningSpaceInBathroom                 otamodel.EnumString = "Width/diameter of wheelchair turning space in bathroom"
	DisabilityFeatureWidthDiameterOfWheelchairTurningSpaceInBedroom                  otamodel.EnumString = "Width/diameter of wheelchair turning space in bedroom"
	DisabilityFeatureWidthDiameterOfWheelchairTurningSpaceInLobbyReceptionArea       otamodel.EnumString = "Width/diameter of wheelchair turning space in lobby/reception area"
)

// otamodel.EnumString Specifies a hotel room location.
const (
	RoomLocationAwayFromTheElevator      otamodel.EnumString = "Away from the elevator"
	RoomLocationBackOfBuilding           otamodel.EnumString = "Back of building"
	RoomLocationConciergeFloor           otamodel.EnumString = "Concierge floor"
	RoomLocationCorner                   otamodel.EnumString = "Corner"
	RoomLocationEast                     otamodel.EnumString = "East"
	RoomLocationFrequentGuestFloor       otamodel.EnumString = "Frequent guest floor"
	RoomLocationFrontOfBuilding          otamodel.EnumString = "Front of building"
	RoomLocationGroundFloor              otamodel.EnumString = "Ground floor"
	RoomLocationHighFloor                otamodel.EnumString = "High floor"
	RoomLocationLobbyLevel               otamodel.EnumString = "Lobby level"
	RoomLocationLowFloor                 otamodel.EnumString = "Low floor"
	RoomLocationNearTheElevator          otamodel.EnumString = "Near the elevator"
	RoomLocationNorth                    otamodel.EnumString = "North"
	RoomLocationAnnexRoom                otamodel.EnumString = "Annex room"
	RoomLocationExecutiveFloor           otamodel.EnumString = "Executive floor"
	RoomLocationGroundFloorInsideAccess  otamodel.EnumString = "Ground floor inside access"
	RoomLocationGroundFloorOutsideAccess otamodel.EnumString = "Ground floor outside access"
	RoomLocationMainBuilding             otamodel.EnumString = "Main building"
	RoomLocationNearStairs               otamodel.EnumString = "Near stairs"
	RoomLocationOther                    otamodel.EnumString = "Other_"
	RoomLocationPoolside                 otamodel.EnumString = "Poolside"
	RoomLocationQuietRoom                otamodel.EnumString = "Quiet room"
	RoomLocationTowerRoom                otamodel.EnumString = "Tower room"
	RoomLocationWingRoom                 otamodel.EnumString = "Wing room"
	RoomLocationSouth                    otamodel.EnumString = "South"
	RoomLocationTopFloor                 otamodel.EnumString = "Top floor"
	RoomLocationWest                     otamodel.EnumString = "West"
)

// otamodel.EnumString Describes room view types
const (
	RoomViewTypeAnnexRoom                otamodel.EnumString = "Annex room"
	RoomViewTypeExecutiveFloor           otamodel.EnumString = "Executive floor"
	RoomViewTypeGroundFloorInsideAccess  otamodel.EnumString = "Ground floor inside access"
	RoomViewTypeGroundFloorOutsideAccess otamodel.EnumString = "Ground floor outside access"
	RoomViewTypeMainBuilding             otamodel.EnumString = "Main building"
	RoomViewTypeNearStairs               otamodel.EnumString = "Near stairs"
	RoomViewTypeOther                    otamodel.EnumString = "Other_"
	RoomViewTypePoolside                 otamodel.EnumString = "Poolside"
	RoomViewTypeQuietRoom                otamodel.EnumString = "Quiet room"
	RoomViewTypeTowerRoom                otamodel.EnumString = "Tower room"
	RoomViewTypeWingRoom                 otamodel.EnumString = "Wing room"
)

// otamodel.EnumString Used to request or specify a gender assignment for a room. Note: Typically used by
// Hosteliers.
const (
	GenderFemale  otamodel.EnumString = "Female"
	GenderUnknown otamodel.EnumString = "Unknown"
	GenderMale    otamodel.EnumString = "Male"
)

// CommunicationLocation Specifies a location for communication.
const (
	CommunicationLocationBusiness    otamodel.EnumString = "Business"
	CommunicationLocationDestination otamodel.EnumString = "Destination"
	CommunicationLocationHome        otamodel.EnumString = "Home"
	CommunicationLocationOther       otamodel.EnumString = "Other_"
)

// AddressUseEnumBase Describes how an address is to be used.
const (
	AddressUseContact          otamodel.EnumString = "Contact"
	AddressUseOther            otamodel.EnumString = "Other_"
	AddressUseBilling          otamodel.EnumString = "Billing"
	AddressUseChain            otamodel.EnumString = "Chain"
	AddressUseCreditCard       otamodel.EnumString = "Credit card"
	AddressUseDelivery         otamodel.EnumString = "Delivery"
	AddressUseDeposit          otamodel.EnumString = "Deposit"
	AddressUseMailing          otamodel.EnumString = "Mailing"
	AddressUsePhysical         otamodel.EnumString = "Physical"
	AddressUsePreOpeningOffice otamodel.EnumString = "Pre-opening office"
)
